#!/usr/bin/expect -f

set ipswitch "10.0.0.10"
set prompt ":admin>"
set prompt2 ":root>"
set ports 47
set portsflag 0

#Login cumulus as admin
spawn ssh -o StrictHostKeyChecking=no admin@$ipswitch
expect "admin@$ipswitch's password: " { send -- "password\r" }

#continuacion de la conf como admin
puts "continuar de manera manual la configuracion de este comando hasta recibir el prompt"
expect "$prompt" { send -- "configure\r" }
interact
